=== youtongluan/sumk/sql.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT sdb (sql+)>
<!ATTLIST sdb
namespace CDATA #IMPLIED
>

<!ELEMENT sql (#PCDATA|if|ifnot|items|foreach)*>
<!ATTLIST sql
id ID #REQUIRED
>

<!ELEMENT if (#PCDATA|if|ifnot|items|foreach)*>
<!ATTLIST if
test CDATA #REQUIRED
falseby (null|nokey|empty) #IMPLIED
>

<!ELEMENT ifnot (#PCDATA|if|ifnot|items|foreach)*>
<!ATTLIST ifnot
test CDATA #REQUIRED
falseby (null|nokey|empty) #IMPLIED
>

<!ELEMENT items (if|ifnot|items|foreach)+>
<!ATTLIST items
separator CDATA #REQUIRED
open CDATA #IMPLIED
close CDATA #IMPLIED
>

<!ELEMENT foreach (#PCDATA)>
<!ATTLIST foreach
collection CDATA #REQUIRED
separator CDATA #REQUIRED
item CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
>

=== youtongluan/sumk/sumk-test/src/test/resources/sql/user/demo.xml
<?xml version="1.0"?>
<!DOCTYPE sdb SYSTEM "https://youtongluan.github.io/sumk/sql.dtd">
<sdb namespace="demo">
<sql id="insert">
	insert into  demo_user (id,name,age,last_update) values (  #{id},#{name},#{age},#{lastUpdate}	  )
</sql>
<sql id="insertBatch">
	insert demo_user (name,age,last_update,id) values
		<foreach collection="list" item="item" separator=",">
			(#{item.name},#{item.age},#{item.lastUpdate},#{item.id})
		</foreach>
</sql>
<sql id="update">
	UPDATE  demo_user       
		   SET  
				name  =   #{name}      ,
				age  =   #{age}      ,
				last_update=#{lastUpdate}
		WHERE 
		<if test="id">id = #{id}</if>
</sql>
<sql id="select">
	select id,name,age,last_update as lastUpdate from ${table} where 1=1
	<if test="id">and id = #{id}</if>
	<if test="name" falseby="empty">and name= #{name}</if><!-- 空字符串会被过滤掉，不作为查询条件 -->
	<if test="age">and age= #{age}</if>
	<if test="lastUpdate">and last_update= #{lastUpdate}</if>
</sql>
<sql id="selectByIds">
	select id,name,age,last_update as lastUpdate from demo_user where id in 
	<foreach collection="ids" item="id" separator="," open="(" close=")">#{id}</foreach>
</sql>
</sdb>

=== youtongluan/sumk/sumk-test/src/test/resources/sql/test.xml
<?xml version="1.0"?>
<!DOCTYPE sdb SYSTEM "https://youtongluan.github.io/sumk/sql.dtd">
<sdb>
<sql id="test1.queryOne">
<!-- ${}转化出来的内容，不能包含表达式 -->
	select * from ${table} where
	1=1 and
	<if test="name | age"> name like #{name} </if>
	<ifnot test="name" falseby="empty"> age=age </ifnot>
	<!-- #{@}是列表项的占位符 ,collection支持集合和数组-->
	<ifnot test="name|id">
		<foreach collection="id" item="tmp"  separator="," open="(" close=")"> id in #{@}</foreach>
	</ifnot>
	limit 10
</sql>

<sql id="selectFirst">
<!-- ${}转化出来的内容，不能包含表达式 -->
	select * from ${table} 
	<![CDATA[
		where id>1234
	]]>
	limit 1
</sql>
<sql id="queryWithName">
	select * from ${table} where
	1=1 and
	 name like #{name} 
	 age=age 
	limit 10
</sql>
<sql id="demouser234314.insert">
	INSERT INTO demo_user (	
				name ,
				id ,
				age,
				enable
	
		)
		VALUES (#{name},#{id},#{age},1) 
</sql>
</sdb>
